name: check

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.2'
          cache: 'npm'
      # key に完全一致するキャッシュが存在したときは true、存在しなかったときは false
      # restore-keys でマッチングしても false
      - uses: actions/cache@v1.0.3
        with:
          # キャッシュとして保存＆復元するディレクトリのパス
          # 絶対パスか working directory からの相対パスを指定する
          path: ~/.npm
          # キャッシュを保存＆復元するためのキー
          # 最大 512 文字で、それ以上の長さの文字列を渡すとエラーになるとのこと
          key: node-${{ hashFiles('**/package-lock.json') }}
          # キャッシュ復元時に key に完全に一致するキャッシュが存在しなかったときに使われるキーのリスト (optional)
          restore-keys: |
            node-
      - name: npm ci
        run: npm ci
      - name: test and lint
        run: npm test
